export const FETCHING_ENTERTAINMENT_DATA = 'FETCH_ENTERTAINMENT_DATA';
export const FETCHING_ENTERTAINMENT_DATA_SUCCESS =
  'FETCH_ENTERTAINMENT_DATA_SUCCESS';
export const FETCHING_ENTERTAINMENT_DATA_ERROR =
  'FETCH_ENTERTAINMENT_DATA_ERROR';
